### ISSUE TITLE
Is there a way to implement drag and drop re-ordering ?

### ISSUE THREAD

**Issue by sandrobilbeisi** [wrike/drag-drop-angular.dart#2]
Awesome ! I really like this DnD implementation
it is very feature complete !

Is there a way to implement drag and drop re-ordering ?

**Comment by bezuglov** [comment]
@sandrobilbeisi Sure. I've added Example22 to show the concept. Check [Live Examples](https://wrike.github.io/drag-drop-angular.dart/).

**Comment by sandrobilbeisi** [comment]
awesome ! thank you very much !
